services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: monitoreo_postgres
    environment:
      POSTGRES_USER: monitoreo_user
      POSTGRES_PASSWORD: monitoreo_pass
      POSTGRES_DB: monitoreo_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/init-data:/docker-entrypoint-initdb.d
      - ./database/backups:/backups
      - ./database/scripts:/scripts
    networks:
      - monitoreo-network
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U monitoreo_user -d monitoreo_dev" ]
      interval: 30s
      timeout: 10s
      retries: 3

  pgadmin:
    image: dpage/pgadmin4
    container_name: monitoreo_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@monitoreo.cl
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8081:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./database/pgadmin-servers.json:/pgadmin4/servers.json
      - ./database/pgadmin-pgpass:/pgadmin4/pgpass
      - ./database/backups:/backups
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - monitoreo-network
    restart: unless-stopped

networks:
  monitoreo-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local
