services:
  # Base de datos PostgreSQL
  postgres:
    image: postgis/postgis:16-3.4
    container_name: vnm_postgres_debug
    environment:
      POSTGRES_DB: monitoreo_dev
      POSTGRES_USER: monitoreo_user
      POSTGRES_PASSWORD: monitoreo_pass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_debug:/var/lib/postgresql/data
      - ./database/init-data:/docker-entrypoint-initdb.d
      - ./database/backups:/backups
      - ./database/scripts:/scripts
    networks:
      - vnm_network_debug
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U monitoreo_user -d monitoreo_dev" ]
      interval: 30s
      timeout: 10s
      retries: 3

  # Backend FastAPI con debugging
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: vnm_backend_debug
    environment:
      - DATABASE_URL=postgresql://monitoreo_user:monitoreo_pass@postgres:5432/monitoreo_dev
      - SECRET_KEY=your-secret-key-here-change-in-production
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
      - ALGORITHM=HS256
      - ENABLE_DEBUG=true # Habilitar debugging
      - WAIT_FOR_CLIENT=false # No esperar debugger por defecto
    ports:
      - "8000:8000" # API
      - "5678:5678" # Puerto de debugging para VS Code
    volumes:
      - ./backend:/app
      - /app/__pycache__ # Excluir cache de Python
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - vnm_network_debug
    restart: unless-stopped
    stdin_open: true
    tty: true
    healthcheck:
      test: ["CMD-SHELL", "python -c \"import requests; requests.get('http://localhost:8000/health', timeout=5)\" || exit 1"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 60s

  # Frontend React con debugging
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: vnm_frontend_debug
    environment:
      - VITE_API_URL=http://localhost:8000/api/v1
      - CHOKIDAR_USEPOLLING=true # Para hot reload en Windows
    ports:
      - "3000:3000" # React dev server
      - "24678:24678" # Puerto adicional para debugging
    volumes:
      - ./frontend:/app
      - /app/node_modules # Excluir node_modules del bind mount
    depends_on:
      - backend
    networks:
      - vnm_network_debug
    restart: unless-stopped
    stdin_open: true
    tty: true
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/ || exit 1"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 90s

networks:
  vnm_network_debug:
    driver: bridge

volumes:
  postgres_data_debug:
    driver: local
